language: python
python: 2.7
env:
    - TOX_ENV=py27
    - TOX_ENV=py33
    - TOX_ENV=pypy

install:
    # Temp solution to multiprocessing travis issue #155
    - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
    - pip install tox coveralls

script: 
    - tox -e $TOX_ENV

after_success: 
    - coveralls

notifications:
  email:
    - john.vrbanac@linux.com
  notifications:
      irc:
          channels:
             - "irc.freenode.org#specterframework"
          use_notice: true
          skip_join: true
