matrix:
  include:
    - language: python
      python: "2.7"
      env: TOXENV=flake8

    - language: python
      python: "2.7"
      env: TOXENV=py27

    - language: python
      python: "3.3"
      env: TOXENV=py33

    - language: python
      python: "3.4"
      env: TOXENV=py34

    - language: python
      python: "3.5"
      env: TOXENV=py35

    - language: python
      python: "3.6"
      env: TOXENV=py36

    - language: python
      python: "pypy"
      env: TOXENV=pypy

install:
    # Temp solution to multiprocessing travis issue #155
    - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
    - pip install tox codecov

script:
    - tox -v

after_success:
    - codecov

notifications:
    irc:
        channels:
            - "chat.freenode.net#specterframework"
        use_notice: true
        skip_join: true
