language: python
python: 2.7
env:
    - TOX_ENV=py27
    - TOX_ENV=py33
    - TOX_ENV=pypy

install:
    # Temp solution to multiprocessing travis issue #155
    - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
    - pip install tox codecov

script:
    - tox -e $TOX_ENV

after_success:
    - codecov

notifications:
    irc:
        channels:
            - "chat.freenode.net#specterframework"
        use_notice: true
        skip_join: true
