language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - pypy
before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
install:
  - pip install -r tools/test-requires --use-mirrors
  - pip install coveralls
  - python setup.py install
script: nosetests --with-coverage
after_success: coveralls
notifications:
  email:
    - john.vrbanac@linux.com
